{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001A3AFE0D2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='3.111.234.240', port=8080): Max retries exceeded with url: /cloud/aws/account (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A3AFE0D2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='3.111.234.240', port=8080): Max retries exceeded with url: /cloud/aws/account (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A3AFE0D2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_rerieve_a_cloud_account[aws]", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001A3B10F8F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='3.111.234.240', port=8080): Max retries exceeded with url: /cloud/azure/account (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A3B10F8F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='3.111.234.240', port=8080): Max retries exceeded with url: /cloud/azure/account (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A3B10F8F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_rerieve_a_cloud_account[azure]", "rerun": "0"}}, "suite_name": "api/cloud/steps/test_cloud_register_steps.py"}}}, "date": "March 05, 2025", "start_time": 1741159898.979809, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "2"}